# This application.yml is only meant as a template, the property values should be over written
# and a new configuration file provided on execution
archiveNotification:
  notificationRepository: /Users/winte/Desktop/notified.txt
  # the period after panel go live when archive (cleanup) will begin.  Use P#Y#M#D to specify the number of years, months, and days respectively
  cleanupPeriod: P0Y6M0D
  # The period before the clean will start when we should send out a notification email.  Use P#Y#M#D to specify the number of years, months, and days respectively
  warningPeriodBeforeCleanup: P0Y2M0D
  emailTemplate:
    # This should only be set if you want messages to go to this address instead of the actually interested parties
    # mockReceiver: Winter.Eric@mayo.edu
    carbonCopy: Winter.Eric@mayo.edu
    # this will be set to true if the email should be an HTML email instead of plain text.  If you need HTML tags or styles use this.
    isHtml: true
    # not in these templates, we substitute $ with ^ in the freemarker templates.  That is so Spring doesn't
    # try to fill in variables.  Spring doesn't currently have a good way to escape them.  This application
    # will replace ^ with $ before filling in the templates.
    ctd: >-
      IMPORTANT - Clinical Test Development (CTD) Data Review for ^{ngs_number}-^{project_name} needed.

      </p>You are receiving this email because you are an owner of <span style='font-weight:bolder;'>^{ngs_number}-^{project_name}</span> data.  Your CTD/Sandbox (i.e. Development)
      data is scheduled to be deleted on <span style='font-weight:bolder;'>^{archive_date}</span> in accordance with the CGSL Clinical Sequencing Data Retention Policy [050548].
      Please refer to this policy for more information.</p>

      <p>If you do NOT want this data deleted at this time, please submit the NGS Data Request Web Form located on the CGSL
      Tools page with the requested information. The request form must be received and approved within one month of the deletion date.</p>

    prod: >-
      IMPORTANT - Production Data Review for ^{ngs_number}-^{project_name} needed.

      <p>You are receiving this email because you are an owner of <span style='font-weight:bolder;'>^{ngs_number}-^{project_name}</span> data.
      Your Production data is scheduled to be archived on <span style='font-weight:bolder;'>^{archive_date}</span> in accordance with the CGSL Clinical Sequencing Data Retention Policy [050548].
      Please refer to this policy for more information on what files are archived and items affected.</p>

      <p>If you do NOT want this data archived at this time, please submit the NGS Data Request Web Form located on the CGSL
      Tools page with the requested information. The request form must be received and approved within one month of the archive date.</p>

# configuration details specific to the connection to SIA
sia:
  # the url where the sia api is deployed
  url: http://r5154431.mayo.edu/projects/siamock/assay-definitions.json

# Spring settings
spring:
  main:
    web-application-type: none
  # this is needed to configure the mail server.  Reference the Spring Mail documentation for details.
  mail:
    default-encoding: UTF-8
    host: fermat.mayo.edu
    #username: lanid
    #password: secret
    port: 25
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    protocol: smtp
    test-connection: false
logging:
  level:
   edu.mayo.cim: DEBUG
